### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by jmvizcainoio** [dask/dask-kubernetes#133]
Hi

i'm trying to configure dask in kubernetes and i have a problems with the workers.

I have deployed dask using helm and replicas worker are 0

I'm using the example code but the script create the pods, but never ends. When i break ctrl+c dump an error form kubernetes.

```
urllib3.exceptions.SSLError: [Errno 2] No such file or directory
```

If i try to configure the scheduler created by helm in the script will return an error.

The code
````
from dask_kubernetes import KubeCluster
import distributed
import dask.array as da

cluster = KubeCluster.from_yaml('worker-spec.yaml' , host="dask-scheduler.default.svc.cluster.local", namespace="default" , port=8786 )


cluster.adapt(minimum=0, maximum=10)  # or dynamically scale based on current workload

client = distributed.Client(cluster)

#
# Create an array and calculate the mean
array = da.ones((1000, 1000, 1000), chunks=(100, 100, 10))
client.compute(array.mean(), True)
print(array.mean().compute())  # Should print 1.0
````

and the error.

````
    backlog=backlog)
  File "/opt/conda/envs/myownenv/lib/python3.7/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
````

Is possible scale up the workers but using the existent scheduler?

Thanks

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

The dask chart you've installed and this project are actually separate things. They are not intended to be used together (although that is something we could work on in the future).

Currently this project creates a cluster on the fly within your notebook kernel.

**Comment by jmvizcainoio** [comment]
Thanks Jacob,

I understand this, but if the workers can connect to the scheduler , what are waiting the dask-kubernetes ? by the error i think that can't see the created pods. 

If a try using the [example](http://kubernetes.dask.org/en/latest/) without helm scheduler i have the same problem.

````
2019-04-09 09:14:53,683 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(FileNotFoundError(2, 'No such file or directory'))': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-jovyan-fa0f18af-2%2Cuser%3Djovyan%2Capp%3Ddask%2Ccomponent%3Ddask-worker
2019-04-09 09:14:53,683 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(FileNotFoundError(2, 'No such file or directory'))': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-jovyan-fa0f18af-2%2Cuser%3Djovyan%2Capp%3Ddask%2Ccomponent%3Ddask-worker
2019-04-09 09:14:53,690 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(FileNotFoundError(2, 'No such file or directory'))': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-jovyan-fa0f18af-2%2Cuser%3Djovyan%2Capp%3Ddask%2Ccomponent%3Ddask-worker
2019-04-09 09:14:53,690 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(FileNotFoundError(2, 'No such file or directory'))': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-jovyan-fa0f18af-2%2Cuser%3Djovyan%2Capp%3Ddask%2Ccomponent%3Ddask-worker
2019-04-09 09:14:53,705 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(FileNotFoundError(2, 'No such file or directory'))': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-jovyan-fa0f18af-2%2Cuser%3Djovyan%2Capp%3Ddask%2Ccomponent%3Ddask-worker
2019-04-09 09:14:53,705 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(FileNotFoundError(2, 'No such file or directory'))': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-jovyan-fa0f18af-2%2Cuser%3Djovyan%2Capp%3Ddask%2Ccomponent%3Ddask-worker
Traceback (most recent call last):
  File "/opt/conda/envs/myownenv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 321, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
FileNotFoundError: [Errno 2] No such file or directory
````
but the pods are running and connected.

````
+ dask-worker --nthreads 2 --no-bokeh --memory-limit 6GB --death-timeout 60
distributed.nanny - INFO -         Start Nanny at: 'tcp://100.96.32.2:45441'
distributed.worker - INFO -       Start worker at:    tcp://100.96.32.2:34547
distributed.worker - INFO -          Listening to:    tcp://100.96.32.2:34547
distributed.worker - INFO -              nanny at:          100.96.32.2:45441
distributed.worker - INFO - Waiting to connect to:    tcp://100.96.31.3:42951
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                    6.00 GB
distributed.worker - INFO -       Local Directory:           /worker-gqb25hug
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:    tcp://100.96.31.3:42951
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Stopping worker at tcp://100.96.32.2:34547
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://100.96.32.2:45441'
````
The ip address 100.96.31.3 is the jupyter pod inside the same k8s cluster.

worker-spec.yaml
````
kind: Pod
metadata:
  labels:
    foo: bar
spec:
  restartPolicy: Never
  containers:
  - image: daskdev/dask:latest
    imagePullPolicy: IfNotPresent
    args: [dask-worker, --nthreads, '2', --no-bokeh, --memory-limit, 6GB, --death-timeout, '60']
    name: dask
    env:
      - name: EXTRA_PIP_PACKAGES
        value: fastparquet git+https://github.com/dask/distributed
  nodeSelector:
    kops.k8s.io/instancegroup: dask-worker
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: dedicate
    operator: Equal
    value: dask-worker
````

test.py

````
from dask_kubernetes import KubeCluster

cluster = KubeCluster.from_yaml('worker-spec1.yaml', clustername='dask')
cluster.scale_up(3)  # specify number of nodes explicitly

#cluster.adapt(minimum=1, maximum=100)  # or dynamically scale based on current workload


# Example usage
import distributed
import dask.array as da

# Connect dask to the cluster
client = distributed.Client(cluster)

# Create an array and calculate the mean
array = da.ones((1000, 1000, 1000), chunks=(100, 100, 10))
print(array.mean().compute())  # Should print 1.0
````

Any idea? I don't know what to look. 

Many thanks by advance.

**Comment by jacobtomlinson** [comment]
```
Traceback (most recent call last):
  File "/opt/conda/envs/myownenv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 321, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
FileNotFoundError: [Errno 2] No such file or directory
```

This error looks like you're missing the ssl cert package in your notebook container.

**Comment by jmvizcainoio** [comment]
I got in .kube/config the cert included in the same file. 

````
- cluster:
    certificate-authority-data: LS0tLS1CRUdJT....
````
I extract the cert to a file and now works fine.

````
- cluster:
    certificate-authority: file.ca
````

But now when finish the test i got an error delete pods

````
1.0
Traceback (most recent call last):
  File "/opt/conda/envs/myownenv/lib/python3.7/weakref.py", line 628, in _exitfunc
    f()
  File "/opt/conda/envs/myownenv/lib/python3.7/weakref.py", line 552, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/opt/conda/envs/myownenv/lib/python3.7/site-packages/dask_kubernetes/core.py", line 511, in _cleanup_pods
    kubernetes.client.V1DeleteOptions())
TypeError: delete_namespaced_pod() takes 3 positional arguments but 4 were given
````

Many thanks

**Comment by mrocklin** [comment]
If you get a chance, can you try the `dev` branch in this repository?

**Comment by jmvizcainoio** [comment]
Hi @mrocklin 

I get this error

`````
/home/jovyan/daskk/dask_kubernetes/config.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fefdd8cbcc0>>, <Task finished coro=<KubeCluster._scale_up() done, defined at /home/jovyan/daskk/dask_kubernetes/core.py:511> exception=AttributeError("'V1Pod' object has no attribute 'openapi_types'")>)
Traceback (most recent call last):
  File "/opt/conda/envs/myownenv/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/opt/conda/envs/myownenv/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/jovyan/daskk/dask_kubernetes/core.py", line 532, in _scale_up
    for _ in range(n - len(pods))
  File "/opt/conda/envs/myownenv/lib/python3.7/site-packages/kubernetes_asyncio/client/api_client.py", line 156, in __call_api
    body = self.sanitize_for_serialization(body)
  File "/opt/conda/envs/myownenv/lib/python3.7/site-packages/kubernetes_asyncio/client/api_client.py", line 220, in sanitize_for_serialization
    for attr, _ in six.iteritems(obj.openapi_types)
AttributeError: 'V1Pod' object has no attribute 'openapi_types'
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fefd7f477b8>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fefd74dc108>, 9894.230988483)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fefd7f47080>
`````

Thanks in advance

**Comment by jacobtomlinson** [comment]
Sorry for the delay in getting back to you. Things have progressed in this project a bit now. If you're still looking at this please try the master branch.

I'm going to close this as potentially stale, but if you're still experiencing issue please ask for it to be reopened.
