### ISSUE TITLE
TypeError: delete_namespaced_pod() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by christianbeland** [dask/dask-kubernetes#135]
Problem when deleting pods:

```
TypeError: delete_namespaced_pod() takes 3 positional arguments but 4 were given
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f4adb8c4eb8>>, <Future finished exception=TypeError('delete_namespaced_pod() takes 3 positional arguments but 4 were given',)>)
Traceback (most recent call last):
  File "/home/user/workspace/dask-dynamic-cluster/venv/lib/python3.5/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/user/workspace/dask-dynamic-cluster/venv/lib/python3.5/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/user/workspace/dask-dynamic-cluster/venv/lib/python3.5/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/user/workspace/dask-dynamic-cluster/venv/lib/python3.5/site-packages/distributed/deploy/adaptive.py", line 327, in _adapt
    f = self.cluster.scale_up(**recommendations)
  File "/home/user/workspace/dask-dynamic-cluster/venv/lib/python3.5/site-packages/dask_kubernetes/core.py", line 437, in scale_up
    pods = pods or self._cleanup_terminated_pods(self.pods())
  File "/home/user/workspace/dask-dynamic-cluster/venv/lib/python3.5/site-packages/dask_kubernetes/core.py", line 421, in _cleanup_terminated_pods
    self._delete_pods(terminated_pods)
  File "/home/user/workspace/dask-dynamic-cluster/venv/lib/python3.5/site-packages/dask_kubernetes/core.py", line 405, in _delete_pods
    kubernetes.client.V1DeleteOptions()
TypeError: delete_namespaced_pod() takes 
```
Any idea?
Is this version related? whre can I find the proper version of all dependencies?

**Comment by jcrist** [comment]
This is the same issue as #118. Kuberenetes 9.0 changed the api here, we'll need to update our code (any interest in making a PR?). Kubernetes < 9.0 should work fine.

**Comment by jcrist** [comment]
Actually someone just submitted a PR at #136.
