### ISSUE TITLE
Timed out when starting dask worker

### ISSUE THREAD

**Issue by lsetiawan** [dask/dask-kubernetes#175]
Hi,

I am new to spinning up dask cluster using the Kubernetes native API. I am trying to follow the example provided but running to an error regarding `Timed out connecting Nanny` and `Timed out starting worker`.

```python
from dask_kubernetes import KubeCluster
cluster = KubeCluster.from_yaml('worker-spec.yml')
cluster.scale(1)
```

I also get an error below when running the lines above:
```
distributed.core - ERROR - add_worker() got an unexpected keyword argument 'extra'
Traceback (most recent call last):
  File "/opt/conda/envs/service/lib/python3.7/site-packages/distributed/core.py", line 412, in handle_comm
    result = handler(comm, **msg)
TypeError: add_worker() got an unexpected keyword argument 'extra'

```

<details><summary><strong>dask worker log</strong></summary>

```bash
dask-anaconda-eb01a0b2-b6hp7c dask distributed.nanny - INFO -         Start Nanny at: 'tcp://100.102.0.5:46267'
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO -       Start worker at:    tcp://100.102.0.5:40937
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO -          Listening to:    tcp://100.102.0.5:40937
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO - Waiting to connect to:    tcp://100.123.0.2:42223
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO - -------------------------------------------------
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO -               Threads:                          1
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO -                Memory:                    2.00 GB
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO -       Local Directory:           /worker-iq4cbovy
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO - -------------------------------------------------
dask-anaconda-eb01a0b2-b6hp7c dask distributed.nanny - INFO - Closing Nanny at 'tcp://100.102.0.5:46267'
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO - Stopping worker at tcp://100.102.0.5:40937
dask-anaconda-eb01a0b2-b6hp7c dask distributed.worker - INFO - Closed worker has not yet started: None
dask-anaconda-eb01a0b2-b6hp7c dask distributed.nanny - ERROR - Timed out connecting Nanny '<Nanny: None, threads: 1>' to scheduler 'tcp://100.123.0.2:42223'
dask-anaconda-eb01a0b2-b6hp7c dask Traceback (most recent call last):
dask-anaconda-eb01a0b2-b6hp7c dask   File "/opt/conda/lib/python3.7/site-packages/distributed/nanny.py", line 309, in instantiate
dask-anaconda-eb01a0b2-b6hp7c dask     timedelta(seconds=self.death_timeout), self.process.start()
dask-anaconda-eb01a0b2-b6hp7c dask tornado.util.TimeoutError: Timeout
dask-anaconda-eb01a0b2-b6hp7c dask distributed.dask_worker - INFO - End worker
dask-anaconda-eb01a0b2-b6hp7c dask Traceback (most recent call last):
dask-anaconda-eb01a0b2-b6hp7c dask   File "/opt/conda/bin/dask-worker", line 10, in <module>
dask-anaconda-eb01a0b2-b6hp7c dask     sys.exit(go())
dask-anaconda-eb01a0b2-b6hp7c dask   File "/opt/conda/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 406, in go
dask-anaconda-eb01a0b2-b6hp7c dask     main()
dask-anaconda-eb01a0b2-b6hp7c dask   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
dask-anaconda-eb01a0b2-b6hp7c dask     return self.main(*args, **kwargs)
dask-anaconda-eb01a0b2-b6hp7c dask   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 717, in main
dask-anaconda-eb01a0b2-b6hp7c dask     rv = self.invoke(ctx)
dask-anaconda-eb01a0b2-b6hp7c dask   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
dask-anaconda-eb01a0b2-b6hp7c dask     return ctx.invoke(self.callback, **ctx.params)
dask-anaconda-eb01a0b2-b6hp7c dask   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
dask-anaconda-eb01a0b2-b6hp7c dask     return callback(*args, **kwargs)
dask-anaconda-eb01a0b2-b6hp7c dask   File "/opt/conda/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 397, in main
dask-anaconda-eb01a0b2-b6hp7c dask     raise TimeoutError("Timed out starting worker.") from None
dask-anaconda-eb01a0b2-b6hp7c dask tornado.util.TimeoutError: Timed out starting worker.

```

</details>

Here are the versions of the libraries that I'm using:
```
Dask version: 2.2.0
Distributed version: 2.2.0
Dask Kubernetes version: 0.9.2
```

Any help would me much appreciated. Thank you in advance :pray:

**Comment by lsetiawan** [comment]
Here's also my worker-spec (nothing much different than the example):
```
kind: Pod
metadata:
  labels:
    foo: bar
spec:
  restartPolicy: Never
  containers:
  - image: daskdev/dask:latest
    imagePullPolicy: IfNotPresent
    args: [dask-worker, --nthreads, '1', --no-bokeh, --memory-limit, 2GB, --death-timeout, '60']
    name: dask
    env:
      - name: EXTRA_PIP_PACKAGES
        value: fastparquet git+https://github.com/dask/distributed
    resources:
      limits:
        cpu: "1"
        memory: 2G
      requests:
        cpu: "1"
        memory: 2G
```

**Comment by mrocklin** [comment]
My guess is that your versions are mismatched.  Probably the value of
`distributed.__version__` is different between the process where you're
running dask-kubernetes and your worker pods.

**Comment by lsetiawan** [comment]
@mrocklin Thank you for the quick reply! I will try matching the versions between the process and the worker pods and report back in a bit.

**Comment by lsetiawan** [comment]
Yepp, sure enough that was the problem. Thanks again @mrocklin :smile: Have a great day!
