### ISSUE TITLE
Error 111 in cleanup

### ISSUE THREAD

**Issue by heavenmarshal** [dask/dask-kubernetes#198]
The task seems to complete successfully. However at the stage of cleaning up worker  pods, I got Error 111. I am using minikube v1.4.0 and docker 19.0.2. The logs are provided below

```
2019-10-22 14:01:22,214 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffb1c8a3e50>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/example/pods?labelSelector=dask.org%2Fcluster-name%3Ddask-root-4f03d8b3-4%2Cuser%3Droot%2Capp%3Ddask
2019-10-22 14:01:22,215 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffb1c8b7050>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/example/pods?labelSelector=dask.org%2Fcluster-name%3Ddask-root-4f03d8b3-4%2Cuser%3Droot%2Capp%3Ddask
2019-10-22 14:01:22,216 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffb1c8b70d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/example/pods?labelSelector=dask.org%2Fcluster-name%3Ddask-root-4f03d8b3-4%2Cuser%3Droot%2Capp%3Ddask
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7ffb1c8b7090>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/weakref.py", line 648, in _exitfunc
    f()
  File "/opt/conda/lib/python3.7/weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))                                                                                                       File "/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py", line 623, in _cleanup_resources
   pods = core_api.list_namespaced_pod(namespace, label_selector=format_labels(labels))
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12372, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12472, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 355, in request
    headers=headers)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /api/v1/namespaces/example/pods?labelSelector=dask.org%2Fcluster-name%3Ddask-root-4f03d8b3-4%2Cuser%3Droot%2Capp%3Ddask (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffb1c8b7090>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

## app.py
```python
import os
import time
from dask_kubernetes import KubeCluster
from dask.distributed import Client

worker_manifest = {
    "kind": "Pod",
    "metadata": {},
    "spec": {"restartPolicy": "Never",
             "containers": [{
                 "name": "worker",
                 "image": "heavenmarshal/dask-k8s-example",
                 "imagePullPolicy": "Always",
                 "command": ["/bin/bash"],
                 "args": ["-c", "dask-worker --nthreads '1' --no-bokeh --memory-limit 100Mi --death-timeout '60'"],
                 "env": [{
                     "name": "EXTRA_PIP_PACKAGES",
                     "value": "fastparquet git+https://github.com/dask/distributed"
                 }]
             }]
    }
}

def add_one(a):
    return a+1

if __name__ == '__main__':
    lst = [1,2]
    namespace = os.getenv("MY_POD_NAMESPACE")
    with KubeCluster.from_dict(worker_manifest, namespace=namespace) as cluster:
        cluster.scale_up(1)
        with Client(cluster) as client:
            results = [client.submit(add_one, a) for a in lst]
            results = client.gather(results)
```

## Dockerfile
```dockerfile
FROM conda/c3i-linux-64
RUN conda install dask=2.6.0 \
	&& conda install -c anaconda distributed=2.6.0 \
	&& conda install -c conda-forge dask-kubernetes=0.10.0 
WORKDIR /app
COPY app.py /app
CMD ["python", "app.py"]
```

## role.yaml
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: example
  name: example-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```
## pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: example
  namespace: example
spec:
  serviceAccountName: example-serviceaccount
  restartPolicy: Never
  containers:
  - name: example
    image: heavenmarshal/dask-k8s-example
    imagePullPolicy: Always
    env:
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
```
rolebinding.yaml and serviceaccount.yaml are omitted.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. It may be related to #29.

Does it manage to clean up the worker pods? Or does it leave them hanging there?

**Comment by heavenmarshal** [comment]
It can clean up the pods anyway. But I think this line is not reached. 
https://github.com/dask/dask-kubernetes/blob/master/dask_kubernetes/core.py#L627
since the log in the next line is now shown.

**Comment by heavenmarshal** [comment]
I did not touch the config files. I use a service account to run it. This service account binds to the role shown in the provided role.yaml. It seems I already give the master pod full control.

**Comment by jacobtomlinson** [comment]
Yeah I think this problem is with the way the cleanup code is authenticating with the cluster.

**Comment by heavenmarshal** [comment]
Tried to rewrite this function
https://github.com/dask/dask-kubernetes/blob/0.10.0/dask_kubernetes/core.py#L617
```python
async def _cleanup_resources(namespace, labels, auth):
    """ Remove all pods with these labels in this namespace """
    import kubernetes

    await ClusterAuth.load_first(auth)
    core_api = kubernetes.client.CoreV1Api()

    pods = core_api.list_namespaced_pod(namespace, label_selector=format_labels(labels))
    for pod in pods.items:
        try:
            core_api.delete_namespaced_pod(pod.metadata.name, namespace)
            logger.info("Deleted pod: %s", pod.metadata.name)
        except kubernetes.client.rest.ApiException as e:
            # ignore error if pod is already removed
            if e.status != 404:
                raise

    services = core_api.list_namespaced_service(
        namespace, label_selector=format_labels(labels)
    )
    for service in services.items:
        try:
            core_api.delete_namespaced_service(service.metadata.name, namespace)
            logger.info("Deleted service: %s", service.metadata.name)
        except kubernetes.client.rest.ApiException as e:
            # ignore error if service is already removed
            if e.status != 404:
                raise
```
It solves the problem. Did not investigate if this could lead to other problems.

**Comment by heavenmarshal** [comment]
insert
```python
kubernetes.config.load_incluster_config()
```
before https://github.com/dask/dask-kubernetes/blob/0.10.0/dask_kubernetes/core.py#L621 could solve my problem.

**Comment by jacobtomlinson** [comment]
Ok that's good to know. That would only work if you are using a service account though, for users who have local config in `~/.kube/config` they would need a different call. We have already wrapped that logic up in the [auth module](https://github.com/dask/dask-kubernetes/blob/master/dask_kubernetes/auth.py). 

I had expected that once we call the auth (either async or sync) it would be configured globally. But it looks like we need to call it for both libraries. I'll look at putting a PR together to fix this.

**Comment by jacobtomlinson** [comment]
@heavenmarshal would you be able to test the changes in #199 and see if they resolve your issue?

**Comment by heavenmarshal** [comment]
seems not work. dask-kubernetes=0+untagged.260.g66235c0.dirty

Traceback (most recent call last):
  File "app.py", line 30, in <module>
    with KubeCluster.from_dict(worker_manifest, namespace=namespace) as cluster:
  File "/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py", line 529, in from_dict
    return cls(make_pod_from_dict(pod_spec), **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py", line 380, in __init__
    super().__init__(**self.kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py", line 242, in __init__
    self.sync(self._start)
  File "/opt/conda/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 162, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 333, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 317, in f
    result[0] = yield future
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py", line 437, in _start
    await ClusterAuth.load_first(self.auth)
  File "/opt/conda/lib/python3.7/site-packages/dask_kubernetes/auth.py", line 71, in load_first
    await auth_instance.load()
  File "/opt/conda/lib/python3.7/site-packages/dask_kubernetes/auth.py", line 126, in load
    self.config_file, self.context, None, self.persist_config
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 645, in load_kube_config
    persist_config=persist_config)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 613, in _get_kube_config_loader_for_yaml_file
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 153, in __init__
    self.set_active_context(active_context)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 173, in set_active_context
    context_name = self._config['current-context']
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 495, in __getitem__
    v = self.safe_get(key)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 491, in safe_get
    key in self.value):
TypeError: argument of type 'NoneType' is not iterable
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f89e289d490>>, <Task finished coro=<SpecCluster._correct_state_internal() done, defined at /opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py:284> exception=AttributeError("'KubeCluster' object has no attribute '_lock'")>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py", line 363, in _close
    await self._correct_state()
  File "/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py", line 285, in _correct_state_internal
    async with self._lock:
AttributeError: 'KubeCluster' object has no attribute '_lock'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 185, in ignoring
    yield
  File "/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py", line 574, in close_clusters
    cluster.close(timeout=10)
  File "/opt/conda/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 83, in close
    return self.sync(self._close, callback_timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 162, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 333, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 317, in f
    result[0] = yield future
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py", line 363, in _close
    await self._correct_state()
  File "/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py", line 285, in _correct_state_internal
    async with self._lock:
AttributeError: 'KubeCluster' object has no attribute '_lock'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f89dd48a550>

**Comment by heavenmarshal** [comment]
It works in my example, the log is

distributed.dashboard.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: pip install jupyter-server-proxy
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:    tcp://172.17.0.4:45679
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.scheduler - INFO - Receive client connection: Client-a738d962-f66a-11e9-8001-0242ac110004
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://172.17.0.5:39577
distributed.scheduler - INFO - Starting worker compute stream, tcp://172.17.0.5:39577
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove client Client-a738d962-f66a-11e9-8001-0242ac110004
distributed.scheduler - INFO - Remove client Client-a738d962-f66a-11e9-8001-0242ac110004
distributed.scheduler - INFO - Close client connection: Client-a738d962-f66a-11e9-8001-0242ac110004
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
distributed.scheduler - INFO - Remove worker tcp://172.17.0.5:39577
distributed.core - INFO - Removing comms to tcp://172.17.0.5:39577
distributed.scheduler - INFO - Lost all workers

Thank you!

**Comment by jacobtomlinson** [comment]
Great thanks for testing it and confirming! I'm going to close this now but please don't hesitate to raise more issues if you have further problems.
