### ISSUE TITLE
Improve documentaton and logging

### ISSUE THREAD

**Issue by StianOvrevage** [dask/dask-kubernetes#227]
I have no luck using dask-kubernetes. Some of the errors are related to WSL (but that should be fixed according to an old issue).

The documentation is also ambigous:
> Currently, it is designed to be run from a pod on a Kubernetes cluster that has permissions to launch other pods. However, it can also work with a remote Kubernetes cluster (configured via a kubeconfig file), as long as it is possible to open network connections with all the workers nodes on the remote cluster. ( https://kubernetes.dask.org/en/latest/ )

I would except a common use case to be developing on a local machine and farming out computations to dask running in the cluster? I might have missed something important but I don't think our data scientists will develop remotely inside an emphemral Pod running in a cluster for a bunch of reasons.

What's unclear to me is 
> open network connections with all the workers nodes

Is that Kubernetes worker nodes because you use NodePorts to expose Pods or is it Dask Workers? If it is the Kubernetes worker nodes that will just never work. No devs have access to the internal Kubernetes network (it kind of defeats the purpose of Kubernetes). Services are exposed via, well, `Services`.

Using the example from the Quick Start gives me this:
```
distributed.dashboard.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: pip install jupyter-server-proxy
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at: tcp://192.168.1.122:50766
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.comm.tcp - WARNING - Could not set timeout on TCP stream: [Errno 92] Protocol not available
distributed.comm.tcp - WARNING - Could not set timeout on TCP stream: [Errno 92] Protocol not available
distributed.comm.tcp - WARNING - Could not set timeout on TCP stream: [Errno 92] Protocol not available
distributed.comm.tcp - WARNING - Could not set timeout on TCP stream: [Errno 92] Protocol not available
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
2020-01-30 15:57:12,542 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f44f8749978>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-stian-d0f18fdf-c%2Cuser%3Dstian%2Capp%3Ddask
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f44f8749978>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-stian-d0f18fdf-c%2Cuser%3Dstian%2Capp%3Ddask
2020-01-30 15:57:12,546 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f44f8749ac8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-stian-d0f18fdf-c%2Cuser%3Dstian%2Capp%3Ddask
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f44f8749ac8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-stian-d0f18fdf-c%2Cuser%3Dstian%2Capp%3Ddask
2020-01-30 15:57:12,548 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f44f8749a20>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-stian-d0f18fdf-c%2Cuser%3Dstian%2Capp%3Ddask
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f44f8749a20>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-stian-d0f18fdf-c%2Cuser%3Dstian%2Capp%3Ddask
Traceback (most recent call last):
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f44f8749c18>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/weakref.py", line 624, in _exitfunc
    f()
  File "/usr/lib/python3.6/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/dask_kubernetes/core.py", line 623, in _cleanup_resources
    pods = core_api.list_namespaced_pod(namespace, label_selector=format_labels(labels))
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12372, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12472, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 355, in request
    headers=headers)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/mnt/d/Data/go/src/github.com/equinor/dask/env/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-stian-d0f18fdf-c%2Cuser%3Dstian%2Capp%3Ddask (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f44f8749c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

I have set up a test application using https://github.com/tomplus/kubernetes_asyncio directly, and it works out of the box like I expect.

Based on the logs I cannot verify which cluster configuration is being used (and why). I've read the source code and tried variations of KubeCluster(), KubeConfig() and KubeAuth() but it fails the same way regardless.

I don't mean to sound snarky, I think dask looks awesome, but the first impression using it on Kubernetes could, to put it mildly, be better :)

**Comment by jacobtomlinson** [comment]
> I would except a common use case to be developing on a local machine and farming out computations to dask running in the cluster? I might have missed something important but I don't think our data scientists will develop remotely inside an emphemral Pod running in a cluster for a bunch of reasons.

The initial use case for this library was based on folks using [Zero to JupyterHub](https://zero-to-jupyterhub.readthedocs.io/en/latest/) or [Binder (specifically the Pangeo Binder)](https://binder.pangeo.io/). Therefore all users are operating from within Jupyter Notebooks running on a Kubernetes cluster. Many data scientists develop remotely within ephemeral pods that have persistent storage attached.

We are currently working on external support where the scheduler is also run in a pod on the cluster and exposed via a service. This is experimental and not currently well documented. If you want to try it out you can set the `deploy_mode='remote'` when creating your `KubeCluster` object. Feedback and testing would be much appreciated.

> Is that Kubernetes worker nodes because you use NodePorts to expose Pods or is it Dask Workers? If it is the Kubernetes worker nodes that will just never work. No devs have access to the internal Kubernetes network (it kind of defeats the purpose of Kubernetes). Services are exposed via, well, Services.

This is referring to the internal Kubernetes network. This is regularly achieved by either running within the cluster (as exampled above) or by using a VPN setup. Not entirely sure what you mean by defeats the point of Kubernetes, there are many use cases for Kubernetes.

> Based on the logs I cannot verify which cluster configuration is being used (and why). I've read the source code and tried variations of KubeCluster(), KubeConfig() and KubeAuth() but it fails the same way regardless.

By default dask-kubernetes should check whether it is in-cluster and has a service account, and if it doesn't find one it will look for your local `.kube/config` file. Looking at your error above it appears that the Kubernetes cluster is refusing the connection to the API. It is interesting that `kubernetes_asyncio` is able to make the connection, we may well have a bug in the way we are detecting credentials, sharing more information around your configuration and setup would be helpful.

> I don't mean to sound snarky, I think dask looks awesome, but the first impression using it on Kubernetes could, to put it mildly, be better :)

Well it sounds like a great opportunity for you to get stuck in and help us improve things here. This is open source software development after all!

**Comment by jacobtomlinson** [comment]
Closing due to inactivity
