### ISSUE TITLE
Executing python script on dask-kubernetes using dask-distributed

### ISSUE THREAD

**Issue by Scarecrow6489** [dask/dask-kubernetes#237]
Trying to deploy a docker container with following python script on a kubernetes cluster using native approach of dask-kubernetes following [this guide](https://docs.dask.org/en/latest/setup/kubernetes.html):
```
cluster = dask_kubernetes.KubeCluster.from_yaml('worker-spec.yaml')
cluster.scale_up(2)
client = distributed.Client(cluster)

# some lines of code
.
.
.
#
dask.compute(var)
```

## Observations:
1. The scheduler-port to which the worker-pod registers (`40595`) & the scheduler-port in the python-code pod (`44709`) are different, but the worker has been created from the python-code pod itself.
2. The worker `Worker 'tcp://10.32.0.84:32843'` that python-code pod tries to register is different from the worker `Start worker at:     tcp://10.32.0.85:40959` in the worker-pod.

-  **What am I doing wrong?** 
- **How to correctly setup dask on kubernetes using the _Native_ approach to execute a _Python script_?**

### dask-worker pod logs:
```
+ '[' '' ']'
no environment.yml
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
+ '[' '' ']'
+ '[' '' ']'
+ exec dask-worker --nthreads 2 --no-bokeh --memory-limit 6GB --death-timeout 60
/opt/conda/lib/python3.7/site-packages/distributed/cli/dask_worker.py:252: UserWarning: The --bokeh/--no-bokeh flag has been renamed to --dashboard/--no-dashboard.
  "The --bokeh/--no-bokeh flag has been renamed to --dashboard/--no-dashboard. "
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.32.0.85:40901'
distributed.worker - INFO -       Start worker at:     tcp://10.32.0.85:40959
distributed.worker - INFO -          Listening to:     tcp://10.32.0.85:40959
distributed.worker - INFO - Waiting to connect to:     tcp://10.32.0.83:40595
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                    6.00 GB
distributed.worker - INFO -       Local Directory:           /worker-swqe6ljb
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:     tcp://10.32.0.83:40595
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.dask_worker - INFO - Exiting on signal 15
distributed.dask_worker - INFO - End worker
```
### python-code pod logs
```
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:    tcp://10.32.0.83:44709
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.scheduler - INFO - Receive client connection: Client-870cd628-57c8-11ea-8007-f66aabff1ac4
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 0, processing: 1>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.0.84:32843
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.32.0.85:36171', name: tcp://10.32.0.85:36171, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.0.85:36171
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 1, processing: 1>
distributed.core - INFO - Removing comms to tcp://10.32.0.84:32843
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 1, processing: 1>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.0.84:32843
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 1, processing: 1>
distributed.core - INFO - Removing comms to tcp://10.32.0.84:32843
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 1, processing: 1>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.0.84:32843
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 1, processing: 1>
distributed.core - INFO - Removing comms to tcp://10.32.0.84:32843
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 1, processing: 1>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.0.84:32843
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 1, processing: 1>
distributed.core - INFO - Removing comms to tcp://10.32.0.84:32843
Traceback (most recent call last):
  File "dask-clean.py", line 79, in <module>
    dask.compute(*(vars()[results[-1]].items()))
  File "/usr/local/lib/python3.6/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/distributed/client.py", line 2576, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/usr/local/lib/python3.6/site-packages/distributed/client.py", line 1874, in gather
    asynchronous=asynchronous,
  File "/usr/local/lib/python3.6/site-packages/distributed/client.py", line 769, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/usr/local/lib/python3.6/site-packages/distributed/utils.py", line 335, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/distributed/utils.py", line 319, in f
    result[0] = yield future
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/distributed/client.py", line 1730, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ('write_data-5e644d0e-24d6-4f72-abbc-c32e08717978', <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 0, processing: 1>)
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.32.0.84:32843', name: tcp://10.32.0.84:32843, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.32.0.84:32843
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.32.0.85:36171', name: tcp://10.32.0.85:36171, memory: 0, processing: 0>
distributed.core - INFO - Removing comms to tcp://10.32.0.85:36171
Task exception was never retrieved
future: <Task finished coro=<BaseTCPConnector.connect() done, defined at /usr/local/lib/python3.6/site-packages/distributed/comm/tcp.py:354> exception=CommClosedError('in <distributed.comm.tcp.TCPConnector object at 0x7f1cde969940>: ConnectionRefusedError: [Errno 111] Connection refused',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/distributed/comm/tcp.py", line 361, in connect
    ip, port, max_buffer_size=MAX_BUFFER_SIZE, **kwargs
  File "/usr/local/lib/python3.6/site-packages/tornado/tcpclient.py", line 280, in connect
    af, addr, stream = await connector.start(connect_timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/tornado/tcpclient.py", line 143, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/distributed/comm/tcp.py", line 373, in connect
    convert_stream_closed_error(self, e)
  File "/usr/local/lib/python3.6/site-packages/distributed/comm/tcp.py", line 130, in convert_stream_closed_error
    raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x7f1cde969940>: ConnectionRefusedError: [Errno 111] Connection refused
2020-02-25 12:15:45,286 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1cd9a7ccc0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-root-702dc62d-b%2Cuser%3Droot%2Capp%3Ddask
2020-02-25 12:15:45,287 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1cd9a7ce10>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-root-702dc62d-b%2Cuser%3Droot%2Capp%3Ddask
2020-02-25 12:15:45,287 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1cd9a7ce80>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-root-702dc62d-b%2Cuser%3Droot%2Capp%3Ddask
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1cd9a7cf28>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/weakref.py", line 624, in _exitfunc
    f()
  File "/usr/local/lib/python3.6/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/local/lib/python3.6/site-packages/dask_kubernetes/core.py", line 623, in _cleanup_resources
    pods = core_api.list_namespaced_pod(namespace, label_selector=format_labels(labels))
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12372, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12472, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 355, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods?labelSelector=foo%3Dbar%2Cdask.org%2Fcluster-name%3Ddask-root-702dc62d-b%2Cuser%3Droot%2Capp%3Ddask (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1cd9a7cf28>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

## Supporting files:
- requirements.txt:
```
bokeh==1.4.0
Click==7.0
cloudpickle==1.2.2
dask==2.9.1
distributed==2.9.1
fsspec==0.6.2
HeapDict==1.0.1
Jinja2==2.10.3
locket==0.2.0
MarkupSafe==1.1.1
msgpack==0.6.2
numpy==1.18.0
packaging==19.2
pandas==0.25.3
partd==1.1.0
Pillow==7.0.0
psutil==5.6.7
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.2
six==1.13.0
sortedcontainers==2.1.0
tblib==1.6.0
toolz==0.10.0
tornado==6.0.3
zict==1.0.0
dask-kubernetes==0.10.0
jupyter-server-proxy==1.2.0
lz4==3.0.2
```

- dockerfile:
```
FROM python:3.6
COPY . /app
WORKDIR /app
RUN pip3 install -r requirements.txt
CMD python3 dask-clean.py
```

- worker-spec.yaml:
```
kind: Pod
metadata:
  labels:
    foo: bar
spec:
  restartPolicy: Never
  volumes:
    - name: dask-volume
      persistentVolumeClaim:
        claimName: dask-volume-claim
  containers:
  - image: daskdev/dask:2.9.1
    imagePullPolicy: IfNotPresent
    args: [dask-worker, --nthreads, '2', --no-bokeh, --memory-limit, 6GB, --death-timeout, '60']
    name: dask
    resources:
      limits:
        cpu: "2"
        memory: 6G
      requests:
        cpu: "2"
        memory: 6G
    volumeMounts:
      - mountPath: "/home/files"
        name: dask-volume
```

**Comment by jacobtomlinson** [comment]
As you closed this issue did you find a solution? If so could you share it for future folks who come across this page?
