### ISSUE TITLE
RuntimeError: Cannot add child handler (on Google Cloud Shell/GKE)

### ISSUE THREAD

**Issue by carderne** [dask/dask-kubernetes#376]
**What happened**:
Running the basic quickstart example with `dask-kubernetes==2021.10.0`, I get the following error (full trace below the fold).

```
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
```

**What you expected to happen**:
Start a basic cluster.

**Minimal Complete Verifiable Example**:
```bash
pip install dask-kubernetes==2021.10.0
```

```python
from dask_kubernetes import KubeCluster
# yaml copied from quickstart
cluster = KubeCluster("worker-spec.yaml")
cluster.scale(1)
```

**Anything else we need to know?**:
It works on version `2021.3.1`.

**Environment**:
- Dask version: 2021.10.0
- Python version: 3.7.3
- Operating System: Debian buster (running on Google Cloud Shell)
- Install method (conda, pip, source): pip

**Comment by carderne** [comment]
```
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    cluster = KubeCluster('worker-spec.yml')
  File "/home/username/.local/lib/python3.7/site-packages/dask_kubernetes/core.py", line 466, in __init__
    super().__init__(**self.kwargs)
  File "/home/username/.local/lib/python3.7/site-packages/distributed/deploy/spec.py", line 275, in __init__
    self.sync(self._start)
  File "/home/username/.local/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 258, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/username/.local/lib/python3.7/site-packages/distributed/utils.py", line 327, in sync
    raise exc.with_traceback(tb)
  File "/home/username/.local/lib/python3.7/site-packages/distributed/utils.py", line 310, in f
    result[0] = yield future
  File "/home/username/.local/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/username/.local/lib/python3.7/site-packages/dask_kubernetes/core.py", line 534, in _start
    await ClusterAuth.load_first(self.auth)
  File "/home/username/.local/lib/python3.7/site-packages/dask_kubernetes/auth.py", line 360, in load_first
    await auth_instance.load()
  File "/home/username/.local/lib/python3.7/site-packages/dask_kubernetes/auth.py", line 420, in load
    await self.load_kube_config()
  File "/home/username/.local/lib/python3.7/site-packages/dask_kubernetes/auth.py", line 443, in load_kube_config
    await loader.load_and_set(config)
  File "/home/username/.local/lib/python3.7/site-packages/kubernetes_asyncio/config/kube_config.py", line 371, in load_and_set
    await self._load_authentication()
  File "/home/username/.local/lib/python3.7/site-packages/kubernetes_asyncio/config/kube_config.py", line 197, in _load_authentication
    await self.load_gcp_token()
  File "/home/username/.local/lib/python3.7/site-packages/dask_kubernetes/auth.py", line 240, in load_gcp_token
    await self.refresh_gcp_token()
  File "/home/username/.local/lib/python3.7/site-packages/dask_kubernetes/auth.py", line 205, in refresh_gcp_token
    credentials = await google_auth_credentials(_config)
  File "/home/username/.local/lib/python3.7/site-packages/kubernetes_asyncio/config/google_auth.py", line 17, in google_auth_credentials
    proc = await cmd_exec
  File "/usr/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1533, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 924, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
```

**Comment by jacobtomlinson** [comment]
Thanks for raising this. Can you confirm you are running Kubernetes on Google Cloud with GKE?

**Comment by carderne** [comment]
Yup

**Comment by jacobtomlinson** [comment]
@drobison00 as you contributed the Google Auth code, would you have some time to take a look at this?

**Comment by drobison00** [comment]
Yes. I'll look into it.

**Comment by jacobtomlinson** [comment]
@drobison00 I just wanted to give another nudge to see if you have some time to look at this?

**Comment by drobison00** [comment]
@jacobtomlinson I don't think there is an issue with the google auth code. It looks more like the call is occurring in a thread/process that doesn't have an asyncio loop started. Looks related: https://bugs.python.org/issue35621

So where its being run, here ("/usr/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec).

@carderne Do you know if this behavior is the same across python versions?

**Comment by carderne** [comment]
Just ran the same code on `python3.9.9` (on Google Cloud Shell) and it seems to work.

**Comment by jacobtomlinson** [comment]
Given that [Dask is looking to drop Python 3.7 support](https://github.com/dask/community/issues/213) in the near future in line with [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) this problem will likely not come up again.

Given we have a workaround of using a newer Python version I'm going to close this out. Thanks for investigating @drobison00 and thanks for testing @carderne.

**Comment by dhirschfeld** [comment]
> this problem will likely not come up again

Jinxed it! I'm seeing this on AKS (1.22.4) with python 3.7.12 and `dask-kubernetes` 2022.1.0
![image](https://user-images.githubusercontent.com/881019/154196081-c34d08ae-a4b4-47e4-8aa6-3b3c7795de3d.png)

The connection then fails with:
```
ApiException: (401)
Reason: Unauthorized
```

Is this a py37 only problem and the fix is to upgrade python?

**Comment by jacobtomlinson** [comment]
Yes this is a known issue in Python 3.7. We are dropping Python 3.7 support soon (dask/community#213) so please upgrade to a more recent version.
