### ISSUE TITLE
Scaling down isn't working for `KubeCluster`

### ISSUE THREAD

**Issue by Matt711** [dask/dask-kubernetes#442]
Scaling down workers isn't working when I call the `scale` method from `KubeCluster`. It's timing out trying to connect to cluster called `simple-cluster`. This is incorrect because it should be connecting to `foo-cluster`.
```bash
[2022-04-26 14:55:52,405] kopf.objects         [ERROR   ] [default/foo-cluster-default-worker-group] Handler 'daskworkergroup_update' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/distributed/comm/core.py", line 289, in connect
    comm = await asyncio.wait_for(
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await fn(**kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/operator/daskcluster.py", line 306, in daskworkergroup_update
    worker_ids = await scheduler.workers_to_close(
  File "/usr/local/lib/python3.8/site-packages/distributed/core.py", line 862, in send_recv_from_rpc
    comm = await self.live_comm()
  File "/usr/local/lib/python3.8/site-packages/distributed/core.py", line 819, in live_comm
    comm = await connect(
  File "/usr/local/lib/python3.8/site-packages/distributed/comm/core.py", line 315, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://simple-cluster.default:8786 after 30 s
```

**Minimal Complete Verifiable Example**:

```python
from dask_kubernetes import KubeCluster
cluster = KubeCluster(name="foo")
cluster.scale(1)
```

**Comment by jacobtomlinson** [comment]
I am also seeing this with running `kubectl scale`. Scaling down just generally seems broken.

**Comment by jacobtomlinson** [comment]
It seems this is because the worker name and pod names are not aligned.
