### ISSUE TITLE
TypeError: str.format() got multiple values for keyword argument 'user'

### ISSUE THREAD

**Issue by mirosval** [dask/dask-kubernetes#453]
When an environment variable `user` is set, the example code from https://kubernetes.dask.org/en/latest/kubecluster.html fails with: 

```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    cluster = KubeCluster(pod_spec, name="trackingmigration")
  File "/lib/python3.10/site-packages/dask_kubernetes/core.py", line 496, in __init__
    super().__init__(**self.kwargs)
  File "/lib/python3.10/site-packages/distributed/deploy/spec.py", line 260, in __init__
    self.sync(self._start)
  File "/lib/python3.10/site-packages/distributed/utils.py", line 318, in sync
    return sync(
  File "/lib/python3.10/site-packages/distributed/utils.py", line 385, in sync
    raise exc.with_traceback(tb)
  File "/lib/python3.10/site-packages/distributed/utils.py", line 358, in f
    result = yield future
  File "/lib/python3.10/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/lib/python3.10/site-packages/dask_kubernetes/core.py", line 572, in _start
    self._generate_name = self._generate_name.format(
TypeError: str.format() got multiple values for keyword argument 'user'
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x119095f90>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1190960b0>
```

This is because https://github.com/dask/dask-kubernetes/blob/main/dask_kubernetes/core.py#L573 doesn't check that it's expanded the same value >1x.

**Comment by jacobtomlinson** [comment]
Thanks for spotting this and suggesting a solution. Do you have any interest in raising a PR to fix this?
