### ISSUE TITLE
Failed to create KubeCluster after upgrading to 2022.4.0 / 2022.4.1

### ISSUE THREAD

**Issue by andrethrill** [dask/dask-kubernetes#466]
**What happened**:

I've been creating `KubeCluster` with:

```python
worker_spec = make_pod_spec(
            extra_pod_config={
                "imagePullSecrets": ...,
                "restartPolicy": "Never",
            },
            extra_container_config={
                "command": None,
                "name": "dask-worker",
            },
            image=...,
            memory_limit=...,
            memory_request=...,
            cpu_limit=...,
            cpu_request=...,
            annotations={
                "cluster-autoscaler.kubernetes.io/safe-to-evict": "false",
            },
)

scheduler_spec = make_pod_spec(
            extra_pod_config={
                "imagePullSecrets": ...,
            },
            extra_container_config={
                "command": None,
                "name": "dask-scheduler",
            },
            image=...,
            memory_limit=...,
            memory_request=...,
            cpu_limit=...,
            cpu_request=...,
            annotations={
                "cluster-autoscaler.kubernetes.io/safe-to-evict": "false",
            },
)

KubeCluster(
    pod_template=worker_spec,
    scheduler_pod_template=scheduler_spec,
    namespace=...,
    idle_timeout=600,
)
```

And it has been working without any problems with 2021.10.0 and 2022.1.0. After upgrading to 2022.4.1 (or 2022.4.0) I'm not able to run `KubeCluster` successfully. The following error is issued:

```
2022-05-10,10:47:00.530 ERROR {global_model} [run] Querying Binary Bot Dataset Failed with exception
Traceback (most recent call last):

(...)

  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/core.py", line 496, in __init__
    super().__init__(**self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 275, in __init__
    self.sync(self._start)
  File "/usr/local/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 220, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/distributed/utils.py", line 327, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/distributed/utils.py", line 310, in f
    result[0] = yield future
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/core.py", line 626, in _start
    await super()._start()
  File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 304, in _start
    self.scheduler = await self.scheduler
  File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 59, in _
    await self.start()
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/core.py", line 198, in start
    logs = await self.logs()
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/core.py", line 118, in logs
    raise e
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/core.py", line 109, in logs
    log = await self.core_api.read_namespaced_pod_log(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 192, in __call_api
    raise e
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 185, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 193, in GET
    return (await self.request("GET", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 187, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: <CIMultiDictProxy('Audit-Id': '31a36776-5258-4a7f-99da-064bcef356ca', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 10 May 2022 10:47:00 GMT', 'Content-Length': '183')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container dask-worker is not valid for pod dask-root-2b3b413a-efzl92","reason":"BadRequest","code":400}
```

**Do I need to change something with this new version?**

**Environment**:

- Dask version: dask[complete]==2021.10.0 and dask[complete]==2022.04.2
- Python version: 3.8.10
- Operating System: ubuntu1604
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
The error seems to be coming from the `read_namespaced_pod_log` request where the container name doesn't line up with the expected name.

Could you try removing the `"name": "dask-worker"` from the `extra_container_config`?

**Comment by andrethrill** [comment]
> The error seems to be coming from the `read_namespaced_pod_log` request where the container name doesn't line up with the expected name.
> 
> Could you try removing the `"name": "dask-worker"` from the `extra_container_config`?

Thanks @jacobtomlinson  indeed, removing the name from `extra_container_config` made it work. Does that mean then that it is currently not possible to give custom names to the containers? (for my use case is not essential, just convenient)

**Comment by jacobtomlinson** [comment]
Glad you have a workaround. It looks like the ability to set custom names if broken right now.

I think this is related to #422 where there was an issue with getting logs from pods with injected sidecar containers. Perhaps something has become disconnected with getting the logs from pods with custom container names. @bstadlbauer would you have some time to take a look?

**Comment by bstadlbauer** [comment]
@jacobtomlinson I think I should be able to help out 👍 I'll try to open a PR tomorrow

**Comment by bstadlbauer** [comment]
@jacobtomlinson A PR which should fix this is out, let me know what you think (#503)

**Comment by jacobtomlinson** [comment]
Many thanks for picking this up @bstadlbauer. I am intending to release this week once the upstream `2022.05.1` release happens.
