### ISSUE TITLE
Operator ServiceAccount doesn't have the right permissions?

### ISSUE THREAD

**Issue by dhirschfeld** [dask/dask-kubernetes#520]
I think #519 may be a consequence of *this* issue.

**What happened**:
When creating an `experimental.KubeCluster` I get the below permission error. The CRDs are installed and my local `kubectl` can connect to the cluster.
```python
cluster = KubeCluster(name='test')
```
```python-traceback
---------------------------------------------------------------------------
ApiException                              Traceback (most recent call last)
File /opt/conda/envs/quantdev/lib/python3.9/site-packages/dask_kubernetes/experimental/kubecluster.py:196, in KubeCluster._create_cluster(self)
    195 try:
--> 196     await custom_objects_api.create_namespaced_custom_object(
    197         group="kubernetes.dask.org",
    198         version="v1",
    199         plural="daskclusters",
    200         namespace=self.namespace,
    201         body=data,
    202     )
    203 except kubernetes.client.ApiException as e:

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/kubernetes_asyncio/client/api_client.py:192, in ApiClient.__call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_types_map, auth_settings, _return_http_data_only, collection_formats, _preload_content, _request_timeout, _host, _request_auth)
    191     e.body = e.body.decode('utf-8') if six.PY3 else e.body
--> 192     raise e
    194 self.last_response = response_data

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/kubernetes_asyncio/client/api_client.py:185, in ApiClient.__call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_types_map, auth_settings, _return_http_data_only, collection_formats, _preload_content, _request_timeout, _host, _request_auth)
    183 try:
    184     # perform request and return response
--> 185     response_data = await self.request(
    186         method, url, query_params=query_params, headers=header_params,
    187         post_params=post_params, body=body,
    188         _preload_content=_preload_content,
    189         _request_timeout=_request_timeout)
    190 except ApiException as e:

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/kubernetes_asyncio/client/rest.py:230, in RESTClientObject.POST(self, url, headers, query_params, post_params, body, _preload_content, _request_timeout)
    227 async def POST(self, url, headers=None, query_params=None,
    228                post_params=None, body=None, _preload_content=True,
    229                _request_timeout=None):
--> 230     return (await self.request("POST", url,
    231                                headers=headers,
    232                                query_params=query_params,
    233                                post_params=post_params,
    234                                _preload_content=_preload_content,
    235                                _request_timeout=_request_timeout,
    236                                body=body))

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/kubernetes_asyncio/client/rest.py:187, in RESTClientObject.request(self, method, url, query_params, headers, body, post_params, _preload_content, _request_timeout)
    186     if not 200 <= r.status <= 299:
--> 187         raise ApiException(http_resp=r)
    189 return r

ApiException: (401)
Reason: Unauthorized
HTTP response headers: <CIMultiDictProxy('Audit-Id': '573cc440-72f1-47dd-93f9-3fc1f096dcad', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Fri, 03 Jun 2022 01:40:23 GMT', 'Content-Length': '129')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}



The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Input In [13], in <cell line: 1>()
----> 1 cluster = KubeCluster(name='test')

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/dask_kubernetes/experimental/kubecluster.py:152, in KubeCluster.__init__(self, name, namespace, image, n_workers, resources, env, auth, port_forward_cluster_ip, create_mode, shutdown_on_close, **kwargs)
    150 if not self.asynchronous:
    151     self._loop_runner.start()
--> 152     self.sync(self._start)

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/distributed/utils.py:320, in SyncMethodMixin.sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    318     return future
    319 else:
--> 320     return sync(
    321         self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    322     )

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/distributed/utils.py:387, in sync(loop, func, callback_timeout, *args, **kwargs)
    385 if error:
    386     typ, exc, tb = error
--> 387     raise exc.with_traceback(tb)
    388 else:
    389     return result

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/distributed/utils.py:360, in sync.<locals>.f()
    358         future = asyncio.wait_for(future, callback_timeout)
    359     future = asyncio.ensure_future(future)
--> 360     result = yield future
    361 except Exception:
    362     error = sys.exc_info()

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/tornado/gen.py:762, in Runner.run(self)
    759 exc_info = None
    761 try:
--> 762     value = future.result()
    763 except Exception:
    764     exc_info = sys.exc_info()

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/dask_kubernetes/experimental/kubecluster.py:178, in KubeCluster._start(self)
    174     raise ValueError(
    175         f"Cluster {self.cluster_name} doesn't and create mode is '{CreateMode.CONNECT_ONLY}'"
    176     )
    177 else:
--> 178     await self._create_cluster()
    180 await super()._start()

File /opt/conda/envs/quantdev/lib/python3.9/site-packages/dask_kubernetes/experimental/kubecluster.py:204, in KubeCluster._create_cluster(self)
    196     await custom_objects_api.create_namespaced_custom_object(
    197         group="kubernetes.dask.org",
    198         version="v1",
   (...)
    201         body=data,
    202     )
    203 except kubernetes.client.ApiException as e:
--> 204     raise RuntimeError(
    205         "Failed to create DaskCluster resource. "
    206         "Are the Dask Custom Resource Definitions installed? "
    207         "https://kubernetes.dask.org/en/latest/operator.html#installing-the-operator"
    208     ) from e
    209 await wait_for_scheduler(cluster_name, self.namespace)
    210 await wait_for_service(core_api, f"{cluster_name}-service", self.namespace)

RuntimeError: Failed to create DaskCluster resource. Are the Dask Custom Resource Definitions installed? https://kubernetes.dask.org/en/latest/operator.html#installing-the-operator
```

In #519 I thought the operator pod logs were telling me that my kube config file wasn't correct (i.e. `kubectl` wasn't working) but after fixing that, creating a `KubeCluster` object raises the permission error in the traceback above.

The operator pod logs show permission errors:
<details>
<summary><tt><b>kubectl -n dask logs pod/dask-operator-dask-kubernetes-operator-5c4f64cf76-kbgx2</b></tt></summary>

```
[2022-06-03 00:25:17,509] kopf._core.reactor.r [DEBUG   ] Starting Kopf 1.35.4.
[2022-06-03 00:25:17,510] kopf.activities.star [DEBUG   ] Activity 'startup' is invoked.
[2022-06-03 00:25:17,511] kopf.activities.star [INFO    ] Activity 'startup' succeeded.
[2022-06-03 00:25:17,511] kopf._core.engines.a [INFO    ] Initial authentication has been initiated.
[2022-06-03 00:25:17,511] kopf.activities.auth [DEBUG   ] Activity 'login_via_client' is invoked.
[2022-06-03 00:25:17,513] kopf.activities.auth [DEBUG   ] Client is configured in cluster with service account.
[2022-06-03 00:25:17,514] kopf.activities.auth [INFO    ] Activity 'login_via_client' succeeded.
[2022-06-03 00:25:17,514] kopf._core.engines.a [INFO    ] Initial authentication has finished.
[2022-06-03 00:25:17,923] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for customresourcedefinitions.v1.apiextensions.k8s.io cluster-wide.
[2022-06-03 00:25:17,924] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for pods.v1 cluster-wide.
[2022-06-03 00:25:17,925] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for daskclusters.v1.kubernetes.dask.org cluster-wide.
[2022-06-03 00:25:17,926] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for daskjobs.v1.kubernetes.dask.org cluster-wide.
[2022-06-03 00:25:17,927] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for daskworkergroups.v1.kubernetes.dask.org cluster-wide.
[2022-06-03 00:25:18,057] kopf._cogs.clients.w [DEBUG   ] Stopping the watch-stream for daskjobs.v1.kubernetes.dask.org cluster-wide.
[2022-06-03 00:25:18,061] kopf._core.reactor.o [ERROR   ] Watcher for daskjobs.v1.kubernetes.dask.org@none has failed: ('daskjobs.kubernetes.dask.org is forbidden: User "system:serviceaccount:dask:dask-operator-dask-kubernetes-operator" cannot list resource "daskjobs" in API group "kubernetes.dask.org" at the cluster scope: Azure does not have opinion for this user.', {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'daskjobs.kubernetes.dask.org is forbidden: User "system:serviceaccount:dask:dask-operator-dask-kubernetes-operator" cannot list resource "daskjobs" in API group "kubernetes.dask.org" at the cluster scope: Azure does not have opinion for this user.', 'reason': 'Forbidden', 'details': {'group': 'kubernetes.dask.org', 'kind': 'daskjobs'}, 'code': 403})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kopf/_cogs/clients/errors.py", line 148, in check_response
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://10.255.0.1:443/apis/kubernetes.dask.org/v1/daskjobs')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 108, in guard
    await coro
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/reactor/queueing.py", line 175, in watcher
    async for raw_event in stream:
  File "/usr/local/lib/python3.8/site-packages/kopf/_cogs/clients/watching.py", line 82, in infinite_watch
    async for raw_event in stream:
  File "/usr/local/lib/python3.8/site-packages/kopf/_cogs/clients/watching.py", line 159, in continuous_watch
    objs, resource_version = await fetching.list_objs(
  File "/usr/local/lib/python3.8/site-packages/kopf/_cogs/clients/fetching.py", line 28, in list_objs
    rsp = await api.get(
  File "/usr/local/lib/python3.8/site-packages/kopf/_cogs/clients/api.py", line 111, in get
    response = await request(
  File "/usr/local/lib/python3.8/site-packages/kopf/_cogs/clients/auth.py", line 45, in wrapper
    return await fn(*args, **kwargs, context=context)
  File "/usr/local/lib/python3.8/site-packages/kopf/_cogs/clients/api.py", line 85, in request
    await errors.check_response(response)  # but do not parse it!
  File "/usr/local/lib/python3.8/site-packages/kopf/_cogs/clients/errors.py", line 150, in check_response
    raise cls(payload, status=response.status) from e
kopf._cogs.clients.errors.APIForbiddenError: ('daskjobs.kubernetes.dask.org is forbidden: User "system:serviceaccount:dask:dask-operator-dask-kubernetes-operator" cannot list resource "daskjobs" in API group "kubernetes.dask.org" at the cluster scope: Azure does not have opinion for this user.', {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'daskjobs.kubernetes.dask.org is forbidden: User "system:serviceaccount:dask:dask-operator-dask-kubernetes-operator" cannot list resource "daskjobs" in API group "kubernetes.dask.org" at the cluster scope: Azure does not have opinion for this user.', 'reason': 'Forbidden', 'details': {'group': 'kubernetes.dask.org', 'kind': 'daskjobs'}, 'code': 403})
```
</details>

Looking more closely at the pod logs is seems the ServiceAccount `dask:dask-operator-dask-kubernetes-operator` doesn't have the necessary permissions?
```
daskjobs.kubernetes.dask.org is forbidden
User "system:serviceaccount:dask:dask-operator-dask-kubernetes-operator"
cannot list resource "daskjobs" in API group "kubernetes.dask.org" at the cluster scope:
Azure does not have opinion for this user.
```

If I look at the `dask-operator-dask-kubernetes-operator-role-cluster` ClusterRole I see:
```
> kubectl describe ClusterRole/dask-operator-dask-kubernetes-operator-role-cluster
Name:         dask-operator-dask-kubernetes-operator-role-cluster
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: dask-operator
              meta.helm.sh/release-namespace: dask
PolicyRule:
  Resources                                                             Non-Resource URLs  Resource Names  Verbs
  ---------                                                             -----------------  --------------  -----
  events                                                                []                 []              [*]
  events.events.k8s.io                                                  []                 []              [*]
  pods                                                                  []                 []              [create delete get watch list]
  services                                                              []                 []              [create delete get watch list]
  mutatingwebhookconfigurations.admissionregistration.k8s.io/v1         []                 []              [create patch]
  validatingwebhookconfigurations.admissionregistration.k8s.io/v1       []                 []              [create patch]
  mutatingwebhookconfigurations.admissionregistration.k8s.io/v1beta1    []                 []              [create patch]
  validatingwebhookconfigurations.admissionregistration.k8s.io/v1beta1  []                 []              [create patch]
  daskclusters.kubernetes.dask.org                                      []                 []              [get list watch patch create delete]
  daskworkergroups.kubernetes.dask.org                                  []                 []              [get list watch patch create delete]
  clusterkopfpeerings.kopf.dev                                          []                 []              [list watch patch get]
  namespaces                                                            []                 []              [list watch]
  customresourcedefinitions.apiextensions.k8s.io                        []                 []              [list watch]
```

**Comment by dhirschfeld** [comment]
In the permissions I see:
```
  Resources                                                             Non-Resource URLs  Resource Names  Verbs
  ---------                                                             -----------------  --------------  -----
  daskclusters.kubernetes.dask.org                                      []                 []              [get list watch patch create delete]
  daskworkergroups.kubernetes.dask.org                                  []                 []              [get list watch patch create delete]
```
But no corresponding `daskjobs.kubernetes.dask.org`.

It seems like the template *should* be creating those permissions?
https://github.com/dask/dask-kubernetes/blob/c64b102ea9f33ae022383b8d0e16f09f6ecef1bd/dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/serviceaccount.yaml#L37-L40

**Comment by dhirschfeld** [comment]
Maybe #512 hasn't made it into a release yet?

**Comment by dhirschfeld** [comment]
> *Maybe https://github.com/dask/dask-kubernetes/pull/512 hasn't made it into a release yet?*

It seems so: https://github.com/dask/dask-kubernetes/compare/2022.5.2...main

**Comment by dhirschfeld** [comment]
Since it appears this has been fixed on `main` I'll close this out.
