### ISSUE TITLE
Lost connection to Pod

### ISSUE THREAD

**Issue by ljstrnadiii** [dask/dask-kubernetes#528]
We currently use HelmCluster with dask_kubernetes `Version: 2022.5.0` and connect with 
```
from dask_kubernetes import HelmCluster
from dask.distributed import Client

cluster = HelmCluster(release_name="dask-deployment", namespace="len")
client = Client("127.0.0.1:8283")
cluster.scale(7)
```
We then port forward with 
`kubectl port-forward --namespace $NAMESPACE svc/${DEPLOYMENT}-scheduler $DASK_SCHEDULER_PORT:8786`, but often see this error show up inconsistently where we run the port forward: 
```
E0616 21:18:40.514060    6424 portforward.go:385] error copying from local connection to remote stream: write tcp 10.0.48.9:47508->35.247.14.206:443: write: connection reset by peer          
E0616 21:18:40.514096    6424 portforward.go:233] lost connection to pod
E0616 21:18:40.514453    6425 portforward.go:233] lost connection to pod
```
and sometimes it is accompanied by errors in python such as

<details>
<summary>Python Errors:</summary>
---------------------------------------------------------------------------
StreamClosedError                         Traceback (most recent call last)
File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/tcp.py:226, in TCP.read(self, deserializers)
    225 try:
--> 226     frames_nbytes = await stream.read_bytes(fmt_size)
    227     (frames_nbytes,) = struct.unpack(fmt, frames_nbytes)

StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

CommClosedError                           Traceback (most recent call last)
File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/core.py:326, in connect(addr, timeout, deserialize, handshake_overrides, **connection_args)
    323 try:
    324     # This would be better, but connections leak if worker is closed quickly
    325     # write, handshake = await asyncio.gather(comm.write(local_info), comm.read())
--> 326     handshake = await asyncio.wait_for(comm.read(), time_left())
    327     await asyncio.wait_for(comm.write(local_info), time_left())

File /opt/conda/envs/ch/lib/python3.8/asyncio/tasks.py:494, in wait_for(fut, timeout, loop)
    493 if fut.done():
--> 494     return fut.result()
    495 else:

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/tcp.py:242, in TCP.read(self, deserializers)
    241     if not sys.is_finalizing():
--> 242         convert_stream_closed_error(self, e)
    243 except Exception:
    244     # Some OSError or a another "low-level" exception. We do not really know what
    245     # was already read from the underlying socket, so it is not even safe to retry
    246     # here using the same stream. The only safe thing to do is to abort.
    247     # (See also GitHub #4133).

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/tcp.py:150, in convert_stream_closed_error(obj, exc)
    149 else:
--> 150     raise CommClosedError(f"in {obj}: {exc}") from exc

CommClosedError: in <TCP (closed)  local=tcp://127.0.0.1:39660 remote=tcp://127.0.0.1:8283>: Stream is closed

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
File <timed exec>:5, in <module>

File /opt/conda/envs/ch/lib/python3.8/site-packages/xgboost/core.py:532, in _deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
    530 for k, arg in zip(sig.parameters, args):
    531     kwargs[k] = arg
--> 532 return f(**kwargs)

File /opt/conda/envs/ch/lib/python3.8/site-packages/xgboost/dask.py:1060, in train(client, params, dtrain, num_boost_round, evals, obj, feval, early_stopping_rounds, xgb_model, verbose_eval, callbacks, custom_metric)
   1058 client = _xgb_get_client(client)
   1059 args = locals()
-> 1060 return client.sync(
   1061     _train_async,
   1062     global_config=config.get_config(),
   1063     dconfig=_get_dask_config(),
   1064     **args,
   1065 )

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/utils.py:318, in SyncMethodMixin.sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    316     return future
    317 else:
--> 318     return sync(
    319         self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    320     )

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/utils.py:385, in sync(loop, func, callback_timeout, *args, **kwargs)
    383 if error:
    384     typ, exc, tb = error
--> 385     raise exc.with_traceback(tb)
    386 else:
    387     return result

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/utils.py:358, in sync.<locals>.f()
    356         future = asyncio.wait_for(future, callback_timeout)
    357     future = asyncio.ensure_future(future)
--> 358     result = yield future
    359 except Exception:
    360     error = sys.exc_info()

File /opt/conda/envs/ch/lib/python3.8/site-packages/tornado/gen.py:762, in Runner.run(self)
    759 exc_info = None
    761 try:
--> 762     value = future.result()
    763 except Exception:
    764     exc_info = sys.exc_info()

File /opt/conda/envs/ch/lib/python3.8/site-packages/xgboost/dask.py:1009, in _train_async(client, global_config, dconfig, params, dtrain, num_boost_round, evals, obj, feval, early_stopping_rounds, verbose_eval, xgb_model, callbacks, custom_metric)
    996     evals_id = []
    998 results = await map_worker_partitions(
    999     client,
   1000     dispatched_train,
   (...)
   1007     workers=workers,
   1008 )
-> 1009 return list(filter(lambda ret: ret is not None, results))[0]

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/multi_lock.py:234, in MultiLock.__aexit__(self, exc_type, exc_value, traceback)
    233 async def __aexit__(self, exc_type, exc_value, traceback):
--> 234     await self.release()

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/core.py:941, in PooledRPCCall.__getattr__.<locals>.send_recv_from_rpc(**kwargs)
    939 if self.deserializers is not None and kwargs.get("deserializers") is None:
    940     kwargs["deserializers"] = self.deserializers
--> 941 comm = await self.pool.connect(self.addr)
    942 prev_name, comm.name = comm.name, "ConnectionPool." + key
    943 try:

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/core.py:1162, in ConnectionPool.connect(self, addr, timeout)
   1160         pass
   1161     raise
-> 1162 return await connect_attempt

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/core.py:1098, in ConnectionPool._connect(self, addr, timeout)
   1096 try:
   1097     self._connecting_count += 1
-> 1098     comm = await connect(
   1099         addr,
   1100         timeout=timeout or self.timeout,
   1101         deserialize=self.deserialize,
   1102         **self.connection_args,
   1103     )
   1104     comm.name = "ConnectionPool"
   1105     comm._pool = weakref.ref(self)

File /opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/core.py:331, in connect(addr, timeout, deserialize, handshake_overrides, **connection_args)
    329     with suppress(Exception):
    330         await comm.close()
--> 331     raise OSError(
    332         f"Timed out during handshake while connecting to {addr} after {timeout} s"
    333     ) from exc
    335 comm.remote_info = handshake
    336 comm.remote_info["address"] = comm._peer_addr

OSError: Timed out during handshake while connecting to tcp://127.0.0.1:8283 after 30 s

2022-06-16 21:14:01,949 - distributed.deploy.cluster - WARNING - Failed to sync cluster info multiple times - perhaps there's a connection issue? Error:
Traceback (most recent call last):
  File "/opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/tcp.py", line 226, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/core.py", line 326, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/opt/conda/envs/ch/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/tcp.py", line 242, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/tcp.py", line 150, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://[::1]:49450 remote=tcp://localhost:49308>: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/ch/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 132, in _sync_cluster_info
    await self.scheduler_comm.set_metadata(
  File "/opt/conda/envs/ch/lib/python3.8/site-packages/distributed/core.py", line 861, in send_recv_from_rpc
    comm = await self.live_comm()
  File "/opt/conda/envs/ch/lib/python3.8/site-packages/distributed/core.py", line 818, in live_comm
    comm = await connect(
  File "/opt/conda/envs/ch/lib/python3.8/site-packages/distributed/comm/core.py", line 331, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://localhost:49308 after 30 s
2022-06-16 21:14:19,605 - distributed.client - ERROR - Failed to reconnect to scheduler after 30.00 seconds, closing client
</details>

**What happened**:
Lost port forwarding connect.
**What you expected to happen**:
To retain a healthy port forward
**Minimal Complete Verifiable Example**:
Ugh, this is really hard because it is totally inconsistent. I don't have a way to replicate the issue, so I can't provide a way for you to do so. 
**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.5.0
- Python version: 3.8.13
- Operating System: Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
- Install method (conda, pip, source): conda

**Comment by ljstrnadiii** [comment]
Apologies if this is not complete enough, but perhaps there is some advice to make this a bit more resilient? I am also just curious if anyone else experiences this.

**Comment by ljstrnadiii** [comment]
It seems that kubectl port-forward is not really designed for this and we are resorting to using the LoadBalancer serviceType. Sorry for the noob fluff issue. Closing
