### ISSUE TITLE
reap_clusters errors due to event loop already running

### ISSUE THREAD

**Issue by kwohlfahrt** [dask/dask-kubernetes#579]
**Describe the issue**:

On Python interpreter shutdown, the `reap_clusters` function runs. This fails if the event loop is already running, which is always the case if a `KubeCluster` exists. This:

1. fails to clean up the cluster if it is not closed
2. presents a spurious error message if the cluster is closed

**Minimal Complete Verifiable Example**:

```
>>> from dask_kubernetes.operator import KubeCluster
>>> k = KubeCluster.from_name("kai-dask")
>>> k.close()
>>> 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/micromamba/envs/main/lib/python3.9/site-packages/dask_kubernetes/operator/kubecluster/kubecluster.py", line 846, in reap_clusters
    loop.run_until_complete(_reap_clusters())
  File "/opt/micromamba/envs/main/lib/python3.9/asyncio/base_events.py", line 623, in run_until_complete
    self._check_running()
  File "/opt/micromamba/envs/main/lib/python3.9/asyncio/base_events.py", line 583, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
sys:1: RuntimeWarning: coroutine 'reap_clusters.<locals>._reap_clusters' was never awaited
```

**Anything else we need to know?**:

Creating a `KubeCluster` causes the loop to start running, so it doesn't seem possible that this reap function could ever work correctly.

```
>>> from dask_kubernetes.operator import KubeCluster
>>> import asyncio
>>> asyncio.get_event_loop().is_running()
False
>>> k = KubeCluster.from_name("kai-dask")
>>> asyncio.get_event_loop().is_running()
True
>>> k.close()
>>> asyncio.get_event_loop().is_running()
True

```

**Environment**:

- Dask version: 2022.10.0
- Python version: 3.9
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
@graingert do you have any thoughts on a good solution for this?

**Comment by baswelsh** [comment]
I hit this one too.  How does this look? Bottom of kubecluster.py.

```diff
@atexit.register
def reap_clusters():
    async def _reap_clusters():
        for cluster in list(KubeCluster._instances):
            if cluster.shutdown_on_close and cluster.status != Status.closed:
                await ClusterAuth.load_first(cluster.auth)
                with suppress(TimeoutError):
                    if cluster.asynchronous:
                        await cluster.close(timeout=10)
                    else:
                        cluster.close(timeout=10)

-    loop = asyncio.get_event_loop()
-    loop.run_until_complete(_reap_clusters())
+   asyncio.run(_reap_clusters())
```

Happy to open a PR.

**Comment by jacobtomlinson** [comment]
A PR would be much appreciated!
