### ISSUE TITLE
Cannot connect to kube-api service

### ISSUE THREAD

**Issue by romanGarvis** [dask/dask-kubernetes#616]
**Describe the issue**:
Getting timeout error to the kube-api service when dask is trying to remove workers

Error logs:
```
2022-11-21 00:34:34 | 2022-11-20 22:34:34,074 - distributed.deploy.adaptive - INFO - Retiring workers [11, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]

2022-11-21 00:35:54 | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.0.0.1:443 ssl:default [None]
  |   | 2022-11-21 00:35:54 | raise client_error(req.connection_key, exc) from exc
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
  |   | 2022-11-21 00:35:54 | transp, proto = await self._wrap_create_connection(
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
  |   | 2022-11-21 00:35:54 | raise last_exc
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
  |   | 2022-11-21 00:35:54 | _, proto = await self._create_direct_connection(req, traces, timeout)
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
  |   | 2022-11-21 00:35:54 | proto = await self._create_connection(req, traces, timeout)
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
  |   | 2022-11-21 00:35:54 | conn = await self._connector.connect(
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
  |   | 2022-11-21 00:35:54 | r = await self.pool_manager.request(**args)
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 177, in request
  |   | 2022-11-21 00:35:54 | return (await self.request("DELETE", url,
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 220, in DELETE
  |   | 2022-11-21 00:35:54 | response_data = await self.request(
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 185, in __call_api
  |   | 2022-11-21 00:35:54 | await self.core_api.delete_namespaced_pod(name, namespace)
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/classic/kubecluster.py", line 96, in close
  |   | 2022-11-21 00:35:54 | await asyncio.gather(*tasks)
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 343, in _correct_state_internal
  |   | 2022-11-21 00:35:54 | await self._correct_state()
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 400, in _
  |   | 2022-11-21 00:35:54 | await self
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 559, in scale_down
  |   | 2022-11-21 00:35:54 | await f
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/distributed/deploy/adaptive.py", line 204, in scale_down
  |   | 2022-11-21 00:35:54 | return await func(*args, **kwargs)
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/distributed/utils.py", line 742, in wrapper
  |   | 2022-11-21 00:35:54 | await self.scale_down(**recommendations)
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/distributed/deploy/adaptive_core.py", line 240, in adapt
  |   | 2022-11-21 00:35:54 | Traceback (most recent call last):
  |   | 2022-11-21 00:35:54 |  
  |   | 2022-11-21 00:35:54 | The above exception was the direct cause of the following exception:
  |   | 2022-11-21 00:35:54 |  
  |   | 2022-11-21 00:35:54 | ConnectionResetError
  |   | 2022-11-21 00:35:54 | await waiter
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
  |   | 2022-11-21 00:35:54 | transport, protocol = await self._create_connection_transport(
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
  |   | 2022-11-21 00:35:54 | return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  |   | 2022-11-21 00:35:54 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
  |   | 2022-11-21 00:35:54 | Traceback (most recent call last):
  |   | 2022-11-21 00:35:54 | 2022-11-20 22:35:53,142 - distributed.deploy.adaptive_core - ERROR - Error during adaptive downscaling. Ignoring.
  |   | 2022-11-21 00:35:52 | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.0.0.1:443 ssl:default [None]
  |   | 2022-11-21 00:35:52 | raise client_error(req.connection_key, exc) from exc
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
  |   | 2022-11-21 00:35:52 | transp, proto = await self._wrap_create_connection(
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
  |   | 2022-11-21 00:35:52 | raise last_exc
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
  |   | 2022-11-21 00:35:52 | _, proto = await self._create_direct_connection(req, traces, timeout)
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
  |   | 2022-11-21 00:35:52 | proto = await self._create_connection(req, traces, timeout)
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
  |   | 2022-11-21 00:35:52 | conn = await self._connector.connect(
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
  |   | 2022-11-21 00:35:52 | r = await self.pool_manager.request(**args)
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 177, in request
  |   | 2022-11-21 00:35:52 | return (await self.request("DELETE", url,
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 220, in DELETE
  |   | 2022-11-21 00:35:52 | response_data = await self.request(
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 185, in __call_api
  |   | 2022-11-21 00:35:52 | await self.core_api.delete_namespaced_pod(name, namespace)
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/classic/kubecluster.py", line 96, in close
  |   | 2022-11-21 00:35:52 | await asyncio.gather(*tasks)
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 343, in _correct_state_internal
  |   | 2022-11-21 00:35:52 | await self._correct_state()
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 400, in _
  |   | 2022-11-21 00:35:52 | await self
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 559, in scale_down
  |   | 2022-11-21 00:35:52 | await f
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/distributed/deploy/adaptive.py", line 204, in scale_down
  |   | 2022-11-21 00:35:52 | return await func(*args, **kwargs)
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/distributed/utils.py", line 742, in wrapper
  |   | 2022-11-21 00:35:52 | Traceback (most recent call last):
  |   | 2022-11-21 00:35:52 |  
  |   | 2022-11-21 00:35:52 | The above exception was the direct cause of the following exception:
  |   | 2022-11-21 00:35:52 |  
  |   | 2022-11-21 00:35:52 | ConnectionResetError
  |   | 2022-11-21 00:35:52 | await waiter
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
  |   | 2022-11-21 00:35:52 | transport, protocol = await self._create_connection_transport(
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
  |   | 2022-11-21 00:35:52 | return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  |   | 2022-11-21 00:35:52 | File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
  |   | 2022-11-21 00:35:52 | Traceback (most recent call last):
  |   | 2022-11-21 00:35:52 | Cannot connect to host 10.0.0.1:443 ssl:default [None]
```

**Environment**:
- AKS version: 1.23.8
- Dask version: 2022.9.1
- Python version: 3.8.15

**Comment by jacobtomlinson** [comment]
Thanks for raising this @romanGarvis. It is strange that the Kuberenetes API becomes unavailable. Do tools like `kubectl` work as expected when you see this error?

Also I just want to point out that you are using the classic implementation of `dask-kubernetes` which we are intending on deprecating. Have you tried the [new implementation](https://kubernetes.dask.org/en/latest/operator.html)?

**Comment by romanGarvis** [comment]
Thank you for your answer @jacobtomlinson 


> Thanks for raising this @romanGarvis. It is strange that the Kuberenetes API becomes unavailable. Do tools like `kubectl` work as expected when you see this error?

Yes. I think it's not related to the Kubernetes API because we're monitoring the endpoint and don't see any abnormal amount of requests or increasing response time.



> Also I just want to point out that you are using the classic implementation of `dask-kubernetes` which we are intending on deprecating. Have you tried the [new implementation](https://kubernetes.dask.org/en/latest/operator.html)?

Not yet, thank you. We need to investigate and implement it. But it's like a long term solution, however we're trying to find the root cause of this issue and fix it ASAP.

**Comment by jacobtomlinson** [comment]
Could you share more information about how you are constructing your cluster? Are you inside k8s or external (if external the port forward could be breaking)?

**Comment by geertjan-garvis** [comment]
> Could you share more information about how you are constructing your cluster? Are you inside k8s or external (if external the port forward could be breaking)?

we're in InCluster mode
```
        cluster = KubeCluster(
            name = cluster_name,
            pod_template = worker_pod_spec,
            scheduler_pod_template = scheduler_pod_spec,
            n_workers = initial_n_workers,
            idle_timeout = idle_timeout,
            auth = [ InCluster() ],
            scheduler_service_wait_timeout = scheduler_service_wait_timeout
        )

```

**Comment by jacobtomlinson** [comment]
I've opened #617 with a potential mitigation to this. Could you try out that branch and see if it works for you? Also as I said I'd recommend migrating to the new implementation, it shouldn't be too much work, shout if you run into any trouble with that.

**Comment by geertjan-garvis** [comment]
thanks @jacobtomlinson , we will try this.
we have indeed kicked off work to move to the new implementation as well

**Comment by romanGarvis** [comment]
> I've opened #617 with a potential mitigation to this. Could you try out that branch and see if it works for you? Also as I said I'd recommend migrating to the new implementation, it shouldn't be too much work, shout if you run into any trouble with that.

Regarding your recommendation we've installed the Operator
```
rkubiv@rkubiv-PC:~/garvis$ helm ls 
NAME	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART                             	APP VERSION
dask	dask-operator	1       	2022-11-22 11:58:19.635999248 +0200 EET	deployed	dask-kubernetes-operator-2022.10.1	2022.4.1 
``` 

and trying to create DaskCluster resource manually 
```
rkubiv@rkubiv-PC:~/garvis$ kubectl get daskclusters
NAME      AGE
example   74m
```

but it doesn't scale pods for scheduler, workers, etc and logs from Operator is empty 

With DaskWorkerGroup it works as expected
```
[2022-11-23 18:35:12,383] kopf.objects         [DEBUG   ] [dask-operator/simple-highmem] Creation is in progress: {'apiVersion': 'kubernetes.dask.org/v1', 'kind': 'DaskWorkerGroup', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"kubernetes.dask.org/v1","kind":"DaskWorkerGroup","metadata":{"annotations":{},"name":"simple-highmem","namespace":"dask-operator"},"spec":{"cluster":"example","worker":{"replicas":2,"spec":{"containers":[{"args":["dask-worker","--name","$(DASK_WORKER_NAME)","--resources","MEMORY=32e9"],"image":"ghcr.io/dask/dask:latest","imagePullPolicy":"IfNotPresent","name":"worker","resources":{"limits":{"memory":"32Gi"},"requests":{"memory":"32Gi"}}}]}}}}\n'}, 'creationTimestamp': '2022-11-23T18:35:12Z', 'generation': 1, 'managedFields': [{'apiVersion': 'kubernetes.dask.org/v1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:cluster': {}, 'f:worker': {'.': {}, 'f:replicas': {}, 'f:spec': {'.': {}, 'f:containers': {}}}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2022-11-23T18:35:12Z'}], 'name': 'simple-highmem', 'namespace': 'dask-operator', 'resourceVersion': '205089927', 'uid': '0dbf3d1f-a773-474d-a554-7ab79138be9b'}, 'spec': {'cluster': 'example', 'worker': {'replicas': 2, 'spec': {'containers': [{'args': ['dask-worker', '--name', '$(DASK_WORKER_NAME)', '--resources', 'MEMORY=32e9'], 'image': 'ghcr.io/dask/dask:latest', 'imagePullPolicy': 'IfNotPresent', 'name': 'worker', 'resources': {'limits': {'memory': '32Gi'}, 'requests': {'memory': '32Gi'}}}]}}}}
[2022-11-23 18:35:12,383] kopf.objects         [DEBUG   ] [dask-operator/simple-highmem] Handler 'daskworkergroup_create' is invoked.
```

From Operator logs don't see that it's watching for DaskCluster resources
```
[2022-11-22 09:58:44,536] kopf._core.reactor.o [WARNING ] Unresolved resources cannot be served (try creating their CRDs): Selector(any_name='daskcluster')
[2022-11-22 09:58:44,537] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for customresourcedefinitions.v1.apiextensions.k8s.io cluster-wide.
[2022-11-22 09:58:44,538] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for daskworkergroups.v1.kubernetes.dask.org cluster-wide.
[2022-11-22 09:58:44,539] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for pods.v1 cluster-wide.
[2022-11-22 09:58:44,540] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for daskjobs.v1.kubernetes.dask.org cluster-wide.
[2022-11-22 09:58:44,541] kopf._cogs.clients.w [DEBUG   ] Starting the watch-stream for daskautoscalers.v1.kubernetes.dask.org cluster-wide.
```

Could you please help?

**Comment by geertjan-garvis** [comment]
@jacobtomlinson -- found the issue, it was failing because we also had a daskclusters CRT for dask gateway:
% kubectl get crd | grep dask
daskautoscalers.kubernetes.dask.org          2022-11-22T09:58:17Z
daskclusters.gateway.dask.org                2022-06-15T12:27:15Z
daskclusters.kubernetes.dask.org             2022-11-22T09:58:18Z
daskjobs.kubernetes.dask.org                 2022-11-22T09:58:18Z
daskworkergroups.kubernetes.dask.org         2022-11-22T09:58:18Z

after removing the dask gateway crd, things seem to be working
is there a way to have both of these coexist?

**Comment by jacobtomlinson** [comment]
Ah sorry about that, they should be able to coexist. I've opened a new issue to track this bug.
