### ISSUE TITLE
Cluster creation fails with scheduler AlreadyExists error

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#654]
I'm seeing an intermittent failure where the scheduler pod has already been created.

```pytb
[2023-02-21 13:34:45,176] kopf.objects         [ERROR   ] [default/rapids-dask-a15ab] Handler 'daskcluster_create_components/status.phase' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await fn(**kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/operator/controller/controller.py", line 235, in daskcluster_create_components
    await api.create_namespaced_pod(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 192, in __call_api
    raise e
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 185, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 230, in POST
    return (await self.request("POST", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 187, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.exceptions.ApiException: (409)
Reason: Conflict
HTTP response headers: <CIMultiDictProxy('Audit-Id': 'ed1cee56-95dd-449b-a8fa-a54664740b7d', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '337f31
48-ad23-4ec0-ad40-565058775761', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'eae3f070-4ce9-451b-ba7b-b62c58882970', 'Date': 'Tue, 21 Feb 2023 13:34:45 GMT', 'Content-Length': '232')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"rapids-dask-a15ab-scheduler\" already exists","reason":"AlreadyExists","details":{"name":"rapids-dask-
a15ab-scheduler","kind":"pods"},"code":409}
[2023-02-21 13:34:45,190] kopf.objects         [WARNING ] [default/rapids-dask-a15ab] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'daskcluster_create_components/status.
phase': {'started': '2023-02-21T13:30:44.023050', 'stopped': None, 'delayed': '2023-02-21T13:35:45.177321', 'purpose': 'update', 'retries': 5, 'success': False, 'failure': False, 'message': '(409)\nReason: Co
nflict\nHTTP response headers: <CIMultiDictProxy(\'Audit-Id\': \'ed1cee56-95dd-449b-a8fa-a54664740b7d\', \'Cache-Control\': \'no-cache, private\', \'Content-Type\': \'application/json\', \'X-Kubernetes-Pf-Flo
wschema-Uid\': \'337f3148-ad23-4ec0-ad40-565058775761\', \'X-Kubernetes-Pf-Prioritylevel-Uid\': \'eae3f070-4ce9-451b-ba7b-b62c58882970\', \'Date\': \'Tue, 21 Feb 2023 13:34:45 GMT\', \'Content-Length\': \'232
\')>\nHTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"rapids-dask-a15ab-scheduler\\" already exists","reason":"AlreadyExists","details":{"name":"rapi
ds-dask-a15ab-scheduler","kind":"pods"},"code":409}\n\n', 'subrefs': None}}}, None),)
```

I think this is happening when a cluster creation fails part way through. The controller attempts to rerun the creation event which then fails because the scheduler pod already got created.

Handlers should be idempotent and the `daskcluster_create_components` handler is not.

**Comment by jacobtomlinson** [comment]
[Kopf docs](https://kopf.readthedocs.io/en/stable/handlers/#event-watching-handlers) say

> It is the developer’s responsibility to make the handlers idempotent (re-executable with no duplicating side-effects).
