### ISSUE TITLE
[Dask Operator] 'daskcluster_create_components/status.phase' failed with an exception

### ISSUE THREAD

**Issue by pl-marasco** [dask/dask-kubernetes#740]
I've been following the [instruction](https://kubernetes.dask.org/en/latest/operator_installation.html#installing-with-helm) to  deploy the operator and everything seems to have been achieved correctly. 
Once I try to invocate the cluster with:
```
from dask_kubernetes.operator import KubeCluster
cluster = KubeCluster(name='test')
```
system rise a timeout  error after having reported that the DaskCluster has been created:

> TimeoutError: Dask Cluster resource not actioned after 60 seconds, is the Dask Operator running?

The log of the dask operator confirms the DaskCluster creation but fails over the creation of cluster components

```
[2023-06-23 08:49:36,277] kopf.objects         [INFO    ] [default/test] DaskCluster test created in default.
[2023-06-23 08:49:36,277] kopf.objects         [INFO    ] [default/test] Handler 'daskcluster_create' succeeded.
[2023-06-23 08:49:36,277] kopf.objects         [INFO    ] [default/test] Creation is processed: 1 succeeded; 0 failed.
[2023-06-23 08:49:36,594] kopf.objects         [INFO    ] [default/test] Creating Dask cluster components.
[2023-06-23 08:49:36,674] kopf.objects         [ERROR   ] [default/test] Handler 'daskcluster_create_components/status.phase' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await fn(**kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/operator/controller/controller.py", line 278, in daskcluster_create_components
    await api.create_namespaced_pod(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 192, in __call_api
    raise e
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 185, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 230, in POST
    return (await self.request("POST", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 187, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: <CIMultiDictProxy('Audit-Id': 'bd26369c-59e1-4bac-9a48-135cf70915d1', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'a58cf3c7-7154-489f-95f0-b199ad38c8ad', 'X-Kubernetes-Pf-Prioritylevel-Uid': '919b7d85-8dd8-429c-b4d2-0d4826eea1f0', 'Date': 'Fri, 23 Jun 2023 08:49:36 GMT', 'Content-Length': '244')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"test-scheduler\" is forbidden: PodSecurityPolicy: unable to admit pod: []","reason":"Forbidden","details":{"name":"test-scheduler","kind":"pods"},"code":403}
[2023-06-23 08:49:36,687] kopf.objects         [WARNING ] [default/test] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'daskcluster_create_components/status.phase': {'started': '2023-06-23T08:49:36.594387', 'stopped': None, 'delayed': '2023-06-23T08:50:36.675816', 'purpose': 'update', 'retries': 1, 'success': False, 'failure': False, 'message': '(403)\nReason: Forbidden\nHTTP response headers: <CIMultiDictProxy(\'Audit-Id\': \'bd26369c-59e1-4bac-9a48-135cf70915d1\', \'Cache-Control\': \'no-cache, private\', \'Content-Type\': \'application/json\', \'X-Kubernetes-Pf-Flowschema-Uid\': \'a58cf3c7-7154-489f-95f0-b199ad38c8ad\', \'X-Kubernetes-Pf-Prioritylevel-Uid\': \'919b7d85-8dd8-429c-b4d2-0d4826eea1f0\', \'Date\': \'Fri, 23 Jun 2023 08:49:36 GMT\', \'Content-Length\': \'244\')>\nHTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"test-scheduler\\" is forbidden: PodSecurityPolicy: unable to admit pod: []","reason":"Forbidden","details":{"name":"test-scheduler","kind":"pods"},"code":403}\n\n', 'subrefs': None}}}, None),)
```

As it seems to be related to the PodSecurityPolicy (maybe I'm wrong) here is the configuration:

```
NAME                      PRIV    CAPS   SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
calico-kube-controllers   false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
calico-node               true           RunAsAny   RunAsAny           MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim,hostPath
calico-typha              false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
magnum.privileged         true    *      RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
tigera-operator           false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            hostPath,configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
```
and the dask-operator role 
```
Name:         dask-kubernetes-operator-1687509769-role-cluster
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: dask-kubernetes-operator-1687509769
              meta.helm.sh/release-namespace: dask-operator
PolicyRule:
  Resources                                                             Non-Resource URLs  Resource Names  Verbs
  ---------                                                             -----------------  --------------  -----
  events                                                                []                 []              [*]
  pods/status                                                           []                 []              [*]
  pods                                                                  []                 []              [*]
  services/status                                                       []                 []              [*]
  services                                                              []                 []              [*]
  events.events.k8s.io                                                  []                 []              [*]
  mutatingwebhookconfigurations.admissionregistration.k8s.io/v1         []                 []              [create patch]
  validatingwebhookconfigurations.admissionregistration.k8s.io/v1       []                 []              [create patch]
  mutatingwebhookconfigurations.admissionregistration.k8s.io/v1beta1    []                 []              [create patch]
  validatingwebhookconfigurations.admissionregistration.k8s.io/v1beta1  []                 []              [create patch]
  daskautoscalers.kubernetes.dask.org                                   []                 []              [get list watch patch create delete]
  daskclusters.kubernetes.dask.org                                      []                 []              [get list watch patch create delete]
  daskjobs.kubernetes.dask.org/status                                   []                 []              [get list watch patch create delete]
  daskjobs.kubernetes.dask.org                                          []                 []              [get list watch patch create delete]
  daskworkergroups.kubernetes.dask.org/scale                            []                 []              [get list watch patch create delete]
  daskworkergroups.kubernetes.dask.org                                  []                 []              [get list watch patch create delete]
  clusterkopfpeerings.kopf.dev                                          []                 []              [list watch patch get]
  namespaces                                                            []                 []              [list watch]
  customresourcedefinitions.apiextensions.k8s.io                        []                 []              [list watch]
```

Is it a misconfiguration or what? 

Environment:

- Kuberetes version: 1.23.5 (deployed on OpenStack / nova) 
- Python env : Python 3.10  Kubernetes 1.24.3 dask-kubernetes  2023.3.2
- Operating System: fedora-coreos-35.20220424.3.0

**Comment by jacobtomlinson** [comment]
It looks like one of your security policies is stopping the Pod from being created. Annoyingly the error doesn't explain which policy is blocking it.

It also looks like [PodSecurityPolocies](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/) were deprecated in Kubernetes 1.21 and removed in 1.25. You mention you are running 1.23.5 which we don't actually support any more in Dask Kubernetes. So I'm hesitant to invest any time in getting to the bottom of this from a project perspective. 

My understanding of PodSecurityPolicies is limited by I think you may need to create a policy to allow the controller to create the Pod resources.

**Comment by pl-marasco** [comment]
Thanks for the tips and definitely I fully understand your perspective. I'll try to see where I'll land with your suggestion.
 
What is the minimum version of K8s supported by the Dask operator? 
unfortunately, all that I found regarding compatibility is either on the main page, where is cited versions 1.22|1.23|1.24|1.25 or [here](https://kubernetes.dask.org/en/latest/installing.html#kubernetes) where I found "at least the current and two previous versions are supported."

**Comment by jacobtomlinson** [comment]
I'm going to close this issue out, but happy to respond to any further comments or questions you might have while you debug this on your end.

**Comment by jacobtomlinson** [comment]
@droctothorpe when you say same issue do you mean related to `PodSecurityPolicies` on k8s 1.23?

**Comment by droctothorpe** [comment]
Thanks for the quick response, @jacobtomlinson. I'm seeing `"daskcluster_create_components/status.phase' failed with an exception"` on K8s 1.22.10.

**Comment by jacobtomlinson** [comment]
@droctothorpe Kubernetes 1.22 went EOL in October last year so we don't test against that version. Are you seeing the same 403 exception or a different one?

**Comment by droctothorpe** [comment]
I'm actually on `1.24.13`. Sorry for the mixup. We're seeing:

```
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator [2023-08-24 16:29:52,731] kopf.objects         [ERROR   ] [nhh829-kf/dask-923089b1-9] Handler 'handle_scheduler_service_status/status' failed with an exception. Will retry.
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator Traceback (most recent call last):
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator   File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator     result = await invoke_handler(
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator   File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator     result = await invocation.invoke(
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator   File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator     result = await fn(**kwargs)  # type: ignore
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator   File "/usr/local/lib/python3.10/site-packages/dask_kubernetes/operator/controller/controller.py", line 350, in handle_scheduler_service_status
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator     cluster = await DaskCluster.get(
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator   File "/usr/local/lib/python3.10/site-packages/kr8s/_objects.py", line 194, in get
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator     raise NotFoundError(f"Could not find {cls.kind} {name}.")
dask-kubernetes-operator-5b58f764f8-dldj7 dask-kubernetes-operator kr8s._exceptions.NotFoundError: Could not find DaskCluster dask-923089b1-9.
```

**Comment by jacobtomlinson** [comment]
@droctothorpe could you try the latest release? That `NotFoundError` looks like it's from an older version because it should include the namespace too.

**Comment by droctothorpe** [comment]
Upgraded to the latest release (2023.9.0) and still running into similar issues unfortunately. The scheduler comes up fine, but when I scale, this happens:

```
│   Error   Logging  17s   kopf  Handler 'daskworkergroup_replica_update/spec.worker.replicas' failed with an exception. Will retry.                                                                                                                                           │
│ Traceback (most recent call last):                                                                                                                                                                                                                                           │
│   File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once                                                                                                                                                          │
│     result = await invoke_handler(                                                                                                                                                                                                                                           │
│   File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler                                                                                                                                                                │
│     result = await invocation.invoke(                                                                                                                                                                                                                                        │
│   File "/usr/local/lib/python3.10/site-packages/kopf/_core/actions/invocation..._                                                                                                                                                                                            │
│     return await anext(self.gen)                                                                                                                                                                                                                                             │
│   File "/usr/local/lib/python3.10/site-packages/kr8s/_api.py", line 133, in call_api                                                                                                                                                                                         │
│     response.raise_for_status()                                                                                                                                                                                                                                              │
│   File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status                                                                                                                                                                             │
│     raise HTTPStatusError(message, request=request, response=self)                                                                                                                                                                                                           │
│ httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://<obfuscate>/apis/apps/v1/namespaces/<obfuscate>-kf/deployments'
```

I'm on K8s 1.24.13.

**Comment by droctothorpe** [comment]
NVM! PBCAK! Sorry! Appreciate the advice.
