### ISSUE TITLE
Does it work for anyone?

### ISSUE THREAD

**Issue by evgolsh** [dask/dask-kubernetes#78]
Hello,

I'm trying to set up Dask and Kubernetes. Dask is version 0.17.5.
Following instructions, I installed dask-kubernetes. It fails with 

> from dask_kubernetes import KubeCluster
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/evg/Library/Python/2.7/lib/python/site-packages/dask_kubernetes/__init__.py", line 1, in <module>
>     from .core import KubeCluster
>   File "/Users/evg/Library/Python/2.7/lib/python/site-packages/dask_kubernetes/core.py", line 7, in <module>
>     from urllib.parse import urlparse
> ImportError: No module named parse
> 

Ok, I'm on Python 2.7, so in core.py I changed 
```python
from urllib.parse import urlparse
```
to
```python
try:
    from urllib.parse import urlparse
except ImportError:
    from urlparse import urlparse
```
and now it fails with

> from dask_kubernetes import KubeCluster
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Library/Python/2.7/site-packages/dask_kubernetes-0.3.0-py2.7.egg/dask_kubernetes/__init__.py", line 1, in <module>
>     from . import config
>   File "/Library/Python/2.7/site-packages/dask_kubernetes-0.3.0-py2.7.egg/dask_kubernetes/config.py", line 10, in <module>
>     dask.config.ensure_file(source=fn)
> AttributeError: 'module' object has no attribute 'config'

**Comment by mrocklin** [comment]
And also yes, dask-kubernetes is used by several groups in production today.

**Comment by mrocklin** [comment]
Any further questions here, or is this good to close?
