### ISSUE TITLE
Task stuck in dask-operator forever

### ISSUE THREAD

**Issue by caren-guo** [dask/dask-kubernetes#810]
**Describe the issue**:

Old task seems to be stuck on dask-operator forever (looks like it's retrying for over 40K times), is there a way to kill the process?

Here's logs from the dask-operator k8s pod:
```
[2023-09-05 23:17:49,916] kopf.objects         [ERROR   ] [ml-adhoc/dask-carenguo-ce3378d5-7] Handler 'handle_scheduler_service_status/status' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await fn(**kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/operator/controller/controller.py", line 331, in handle_scheduler_service_status
    cluster = await DaskCluster.objects(api, namespace=namespace).get_by_name(
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/aiopykube/query.py", line 19, in get_by_name
    return await self._sync(super().get_by_name, name=name)
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/aiopykube/mixins.py", line 9, in _sync
    return await asyncio.get_event_loop().run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pykube/query.py", line 116, in get_by_name
    raise ObjectDoesNotExist(f"{name} does not exist.")
pykube.exceptions.ObjectDoesNotExist: dask-carenguo-ce3378d5-7 does not exist.
[2023-09-05 23:17:49,936] kopf.objects         [WARNING ] [ml-adhoc/dask-carenguo-ce3378d5-7] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'handle_scheduler_service_status/status': {'started': '2023-08-03T18:46:47.557042', 'stopped': None, 'delayed': '2023-09-05T23:18:49.917133', 'purpose': 'create', 'retries': 47676, 'success': False, 'failure': False, 'message': 'dask-carenguo-ce3378d5-7 does not exist.', 'subrefs': None}}}, None),)
```

**Minimal Complete Verifiable Example**:

I wasn't sure what had caused it exactly. I may have called `KubeCluster.from_name()` with the wrong name on a pod and the pod was terminated unexpectedly.

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.3.2
- Python version: 3.8
- Operating System: Linux (on k8s cluster)
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
Thanks for raising this. The code that is failing here has been removed recently so I expect upgrading to the latest release will resolve this.
